import type { NextPage, GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { getRandomPicture } from '@/api/unsplash';
import { Picture } from '@/api/entities';
import { yearsDiff } from '@/pageSrc/home/utils';
import styles from '@/pageSrc/home/styles.module.css';
import RenderBlur from '@/components/RenderBlur';
import UAParser from 'ua-parser-js';
import isDarkColor from 'is-dark-color';

const Home: NextPage<Props> = ({
  rustaceanSince,
  experiencedSince,
  picture,
}) => {
  const since = new Date(experiencedSince);
  const rustSince = new Date(rustaceanSince);
  const imgUrl = `${picture.links.download}&crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-1.2.1&w=2000&q=80`;
  const isDark = isDarkColor(picture.color ?? '#000');

  return (
    <div className={styles.container}>
      <Head>
        <title>Victor Quiroz Castro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <RenderBlur blurHash={picture.blur_hash ?? ''} url={imgUrl}>
          {(isReady) => (
            <div
              className={styles.picture__wrapper}
              style={{
                backgroundImage: `url(${imgUrl})`,
                opacity: isReady ? 1 : 0,
              }}
            ></div>
          )}
        </RenderBlur>
        <div
          className={styles.about_me}
          style={{
            color: isDarkColor(picture.color ?? '#000') ? '#fafafa' : '#333',
          }}
        >
          <div>
            <h1 className={styles.title}>Victor Quiroz Castro</h1>
            <h2 className={styles.subtitle}>Software Engineer</h2>
            <p className={styles.text}>
              <a className={styles.link} href="https://github.com/victorhqc">
                @victorhqc
              </a>
            </p>
          </div>
          <div>
            <h1 className={styles.title}>About Me</h1>
            <p className={styles.text}>
              I'm a Software Engineer with {yearsDiff(since)} of experience with
              JavaScript & Web Technologies and {yearsDiff(rustSince)} years of
              experience with Rust.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export async function getServerSideProps(
  context: GetServerSidePropsContext
): Promise<{ props: Props }> {
  const picture = await getRandomPicture();
  const parser = new UAParser(context.req.headers['user-agent']);

  return {
    props: {
      picture,
      os: parser.getOS(),
      experiencedSince: '2010-06-30',
      rustaceanSince: '2019-04-01',
    },
  };
}

type Props = {
  picture: Picture;
  os: UAParser.IOS;
  experiencedSince: string;
  rustaceanSince: string;
};

export default Home;
