import type { NextPage, GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { decode } from 'blurhash';
import { createCanvas } from '@napi-rs/canvas';
import { getRandomPicture } from '@/api/unsplash';
import { Picture } from '@/api/entities';
import { yearsDiff, isMobile } from '@/pageSrc/home/utils';
import styles from '@/pageSrc/home/styles.module.css';
import RenderBlur from '@/components/RenderBlur';
import UAParser from 'ua-parser-js';
import isDarkColor from 'is-dark-color';

const Home: NextPage<Props> = ({
  rustaceanSince,
  experiencedSince,
  picture,
  isMobile,
  blur,
}) => {
  const since = new Date(experiencedSince);
  const rustSince = new Date(rustaceanSince);
  const desiredWidth = isMobile ? 800 : 2000;
  const imgUrl = `${picture.links.download}&crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-1.2.1&w=${desiredWidth}&q=80`;
  const isDark = isDarkColor(picture.color ?? '#000');

  return (
    <div className={styles.container}>
      <Head>
        <title>Victor Quiroz Castro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <RenderBlur blur={blur} url={imgUrl}>
          {({ imageLoaded }) => (
            <div
              className={styles.picture__wrapper}
              style={{
                backgroundImage: `url(${imgUrl})`,
                opacity: imageLoaded ? 1 : 0,
              }}
              role="img"
              aria-label={picture.alt_description ?? 'background picture'}
            ></div>
          )}
        </RenderBlur>
        <div
          className={styles.about_me}
          style={{
            color: isDark ? '#fafafa' : '#333',
            backgroundColor: picture.color ?? '#fff',
          }}
        >
          <div>
            <h1 className={styles.title}>Victor Quiroz Castro</h1>
            <h2 className={styles.subtitle}>Software Engineer</h2>
            <p className={styles.text}>
              <a className={styles.link} href="https://github.com/victorhqc">
                @victorhqc
              </a>
            </p>
          </div>
          <div>
            <h1 className={styles.title}>About Me</h1>
            <p className={styles.text}>
              I&apos;m a Software Engineer with {yearsDiff(since)} of experience
              with JavaScript & Web Technologies and {yearsDiff(rustSince)}{' '}
              years of experience with Rust.
            </p>
          </div>
        </div>
      </main>
      <footer
        className={styles.picture__about}
        style={{ color: isDark ? '#fafafa' : '#333' }}
      >
        <p>
          Picture taken by <a href={picture.links.html}>{picture.user.name}</a>
        </p>
      </footer>
    </div>
  );
};

export async function getServerSideProps(
  context: GetServerSidePropsContext
): Promise<{ props: Props }> {
  const parser = new UAParser(context.req.headers['user-agent']);
  const orientation = isMobile(parser) ? 'portrait' : 'landscape';
  const picture = await getRandomPicture(undefined, orientation);

  return {
    props: {
      picture,
      blur: generateBlur(
        picture.blur_hash ?? '',
        isMobile(parser) ? 400 : 900,
        isMobile(parser) ? 800 : 600
      ),
      isMobile: isMobile(parser),
      experiencedSince: '2010-06-30',
      rustaceanSince: '2019-04-01',
    },
  };
}

function generateBlur(
  blurHash: string,
  width: number = 160,
  height: number = 120,
  punch?: number
) {
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');
  const imageData = ctx.createImageData(width, height);

  const pixels = decode(blurHash, width, height, punch);
  imageData.data.set(pixels);

  ctx.putImageData(imageData, 0, 0);

  return canvas.toDataURL();
}

type Props = {
  picture: Picture;
  experiencedSince: string;
  rustaceanSince: string;
  isMobile: boolean;
  blur: string;
};

export default Home;
