
type ExifMeta {
	id: ID!
	iso: Int!
	focalLength: Float!
	exposureCompensation: Float!
	aperture: Float!
	maker: Maker!
	cropFactor: Float!
	cameraName: String!
	lensName: String
}

enum FileType {
	JPEG
}




enum Maker {
	FUJIFILM
	KONICA
	CANON
}

type Photo {
	id: ID!
	src: String!
	filename: String!
	rating: Int!
	filetype: FileType!
	dateTaken: String
	city: String
	createdAt: String!
	updatedAt: String!
	deleted: Boolean!
	exifMeta: ExifMeta!
}

type RootQuery {
	photo(id: ID!): Photo!
	exifMeta(id: ID!): ExifMeta!
}


directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
schema {
	query: RootQuery
}
