[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
log = "0.4.21"
pretty_env_logger = "0.5.0"
rocket = "0.5.0"
serde = { version = "1.0.201", features = ["derive"] }
snafu = "0.8.2"
sqlx = { version = "0.7.4", features = [ "sqlite", "runtime-tokio", "macros", "migrate", "time" ] }
strum = "0.26.2"
strum_macros = "0.26.2"
time = "0.3.36"
