
enum CameraMaker {
	FUJIFILM
	KONICA
	CANON
}

type ExifMeta {
	id: ID!
	rating: Int!
	city: String
	dateTaken: String
	iso: Int!
	aperture: Float!
	shutterSpeed: String!
	focalLength: FocalLength!
	exposureCompensation: Float!
	cameraMaker: CameraMaker!
	lensMaker: LensMaker!
	cameraName: String!
	lensName: String
	fujifilmRecipe: FujifilmRecipe
}

enum FileType {
	JPEG
}


type FocalLength {
	value: Float!
	eq35Mm: Float!
	cropFactor: Float!
}

type FujifilmRecipe {
	id: ID!
	name: String!
	src: String!
	filmSimulation: String!
	sensor: String!
	settings: FujifilmRecipeSettings!
}

union FujifilmRecipeSettings = FujifilmRecipeTransISettings | FujifilmRecipeTransIISettings | FujifilmRecipeTransIIISettings | FujifilmRecipeTransIVSettings | FujifilmRecipeTransVSettings

type FujifilmRecipeTransIIISettings {
	whiteBalance: String!
	dynamicRange: String!
	grainEffect: String!
	toneCurve: String!
	color: String!
	monochromaticColor: String!
	sharpness: String!
	highIsoNoiseReduction: String!
}

type FujifilmRecipeTransIISettings {
	whiteBalance: String!
	dynamicRange: String!
	toneCurve: String!
	color: String!
	sharpness: String!
	highIsoNoiseReduction: String!
}

type FujifilmRecipeTransISettings {
	whiteBalance: String!
	dynamicRange: String!
	toneCurve: String!
	color: String!
	sharpness: String!
	highIsoNoiseReduction: String!
}

type FujifilmRecipeTransIVSettings {
	whiteBalance: String!
	dynamicRange: String!
	dRangePriority: String!
	grainEffect: String!
	colorChromeEffect: String!
	colorChromeFxBlue: String!
	toneCurve: String!
	color: String!
	monochromaticColor: String!
	sharpness: String!
	highIsoNoiseReduction: String!
	clarity: String!
}

type FujifilmRecipeTransVSettings {
	whiteBalance: String!
	dynamicRange: String!
	dRangePriority: String!
	grainEffect: String!
	colorChromeEffect: String!
	colorChromeFxBlue: String!
	toneCurve: String!
	color: String!
	monochromaticColor: String!
	sharpness: String!
	highIsoNoiseReduction: String!
	clarity: String!
}



enum LensMaker {
	FUJIFILM
	KONICA
	CANON
	SEVEN_ARTISANS
	UNKNOWN
}

type Photo {
	id: ID!
	title: String!
	src: String!
	filename: String!
	filetype: FileType!
	createdAt: String!
	updatedAt: String!
	deleted: Boolean!
	exifMeta: ExifMeta!
	tags: [Tag!]!
}

input PhotosQueryInput {
	tag: String
	maxResults: Int
}

type RootQuery {
	photo(id: ID!): Photo!
	photos(input: PhotosQueryInput!): [Photo!]!
	exifMeta(id: ID!): ExifMeta!
	tag(name: String!): Tag!
	fujifilmRecipes(filmSimulation: String!): [FujifilmRecipe!]!
}


type Tag {
	id: ID!
	name: String!
	createdAt: String!
	updatedAt: String!
	deleted: Boolean!
	photos: [Photo!]!
}

directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
schema {
	query: RootQuery
}
