name: Deploy Release

# on: [push]
on:
  release:
    types: [created]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Build Server
        uses: rust-build/rust-build.action@v1.3.2
        env:
          SRC_DIR: api.victorhqc.com
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          UNSPLASH_IMAGE_CACHE_IN_MINS: 60
          UNSPLASH_API_URL: https://api.unsplash.com
          UNSPLASH_ACCESS_KEY: ${{secrets.UNSPLASH_ACCESS_KEY}}
          UNSPLASH_SECRET_KEY: ${{secrets.UNSPLASH_SECRET_KEY}}
        with:
          RUSTTARGET: ${{ matrix.target }}

  deploy:
    needs: build
    name: Deploy Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download Binary
        run: |
          cd ./api.victorhqc.com/scripts/
          node --experimental-fetch ./download_binary.js
        shell: bash
        env:
          GH_REPO: ${{ github.api_url }}/repos/${{ github.repository }}
          GH_TAGS: ${{ github.api_url }}/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}
          TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: debug data
        run: |
          ls -la
          cd api.victorhqc.com
          ls -la
        shell: bash
      - name: Upload Binary
        run: |
          scp -i ${{ env.SSH_KEY_PATH }} ./api.victorhqc.com/api_victorhqc_com.zip github@159.65.35.29:/home/github
        shell: bash
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Commit Deploy
        run: |
          ssh -i ${{ env.SSH_KEY_PATH }} github@159.65.35.29 'unzip api_victorhqc_com.zip | sudo systemctl restart api.victorhqc.com'
        shell: bash
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
