name: Deploy Release

on: [push]
# on:
#   release:
#     types: [created]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      # - uses: actions/setup-node@v1
      #   with:
      #       node-version: "16.x"
      # - name: Install rust stable
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true
      - name: Build Server
        uses: rust-build/rust-build.action@v1.3.2
        # run: |
        #   cargo build --release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          UNSPLASH_IMAGE_CACHE_IN_MINS: 60
          UNSPLASH_API_URL: https://api.unsplash.com
          UNSPLASH_ACCESS_KEY: ${{secrets.UNSPLASH_ACCESS_KEY}}
          UNSPLASH_SECRET_KEY: ${{secrets.UNSPLASH_SECRET_KEY}}
        with:
          RUSTTARGET: ${{ matrix.target }}
        # EXTRA_FILES: "README.md LICENSE"

  deploy:
    needs: build
    name: Deploy Binary
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Download Binary
        run: |
          ssh -i $SSH_KEY_PATH github@159.65.35.29 'pwd'
        shell: bash
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
