name: Deploy Release

# on: [push]
on:
  release:
    types: [created]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Build Server
        uses: rust-build/rust-build.action@v1.3.2
        env:
          SRC_DIR: api.victorhqc.com
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          UNSPLASH_IMAGE_CACHE_IN_MINS: 60
          UNSPLASH_API_URL: https://api.unsplash.com
          UNSPLASH_ACCESS_KEY: ${{secrets.UNSPLASH_ACCESS_KEY}}
          UNSPLASH_SECRET_KEY: ${{secrets.UNSPLASH_SECRET_KEY}}
        with:
          RUSTTARGET: ${{ matrix.target }}

  deploy:
    # needs: build
    name: Deploy Binary
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Data
        run: |
          curl -o /dev/null -sH "${{ env.AUTH }}" ${{ env.GH_REPO }} || { echo "Error: Invalid repo, token or network issue!";  exit 1; }

          response=$(curl -sH "${{ env.AUTH }}" ${{ env.GH_TAGS }})

          eval $(echo "$response" | grep -C3 "name.:.\+$name" | grep -w id | tr : = | tr -cd '[[:alnum:]]=')
          [ "$id" ] || { echo "Error: Failed to get asset id, response: $response" | awk 'length($0)<100' >&2; exit 1; }
          GH_ASSET="${{ env.GH_REPO }}/releases/assets/$id"
          echo "GH_ASSET=$GH_ASSET" >> $GITHUB_ENV
        env:
          GH_REPO: ${{ github.api_url }}/repos/${{ github.repository }}
          GH_TAGS: ${{ env.GH_REPO }}/releases/tags/${{ github.ref_name }}
          AUTH: "Authorization: token ${{ secrets.GH_TOKEN }}"
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Download Binary
        run: |
          echo "binary location"
          echo ${{ env.GH_ASSET }}
          # ssh -i $SSH_KEY_PATH github@159.65.35.29
          # ssh -i $SSH_KEY_PATH github@159.65.35.29 "curl -vLJO -H 'Authorization: token $GITHUB_TOKEN' 'https://api.github.com/repos/victorhqc/victorhqc.com/releases/assets/:id'"
        shell: bash
        env:
          GH_REPO: ${{ github.api_url }}/repos/${{ github.repository }}
          GH_TAGS: ${{ env.GH_REPO }}/releases/tags/${{ github.ref_name }}
          AUTH: "Authorization: token ${{ secrets.GH_TOKEN }}"
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
