name: Release

on:
    push:
        tags:
            - "v*"
        paths-ignore:
            - "**/Cargo.toml"

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_release:
        name: Build and Release
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                      api_artifact_name: linux-api-victorhqc-com
                      cli_artifact_name: linux-cli-victorhqc-com
                      web_artifact_name: linux-web-victorhqc-com

        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install latest stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  target: ${{ matrix.target }}
                  profile: minimal

            - uses: Swatinem/rust-cache@v2
              with:
                  workspaces: |
                      api
                      web
                      core
                      cli
                  cache-on-failure: true
                  shared-key: "rust-cache"

            - name: Install musl tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y musl-tools

            - name: Build Release Binary
              run: cargo build --release --target ${{ matrix.target }}

            - name: Rename binaries
              shell: bash
              run: |
                  mv target/${{ matrix.target }}/release/api-victorhqc-com ${{ matrix.api_artifact_name }}
                  mv target/${{ matrix.target }}/release/cli-victorhqc-com ${{ matrix.cli_artifact_name }}
                  mv target/${{ matrix.target }}/release/web-victorhqc-com ${{ matrix.web_artifact_name }}

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      ${{ matrix.api_artifact_name }}
                      ${{ matrix.cli_artifact_name }}
                      ${{ matrix.web_artifact_name }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
